#!/bin/bash

# Install URNetwork provider
curl -fSsL https://raw.githubusercontent.com/urnetwork/connect/refs/heads/main/scripts/Provider_Install_Linux.sh | sh

# Reload shell config
source ~/.bashrc

# Buat folder dan simpan JWT
mkdir -p /root/.urnetwork
printf '%s' 'eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdXRoX3Nlc3Npb25faWRzIjpbIjAxOThiOGZkLTBjYTAtODM1OS05YzRmLTJlOWQ0OGMyMWQwMyJdLCJjcmVhdGVfdGltZSI6IjIwMjUtMDUtMzFUMTQ6NTY6NDMuNjQxMjcyWiIsIm5ldHdvcmtfaWQiOiIwMTk3MjZkOC01ZTc1LThjNjItMjcxOS0zYjBjOGUzNzJjNzMiLCJuZXR3b3JrX25hbWUiOiJtYWplc3R5eWVhcmkiLCJ1c2VyX2lkIjoiMDE5NzI2ZDgtNWU3NS04YzYyLTI3MTktM2IwYzViYzc2MDg5In0.FVaqQ235bk_oBMIpdJB3qiGu0c61Id_sMKMfIV3BmNMTiVlE1JEr9WSAfDGSXf20Yq6T7btU8P9plMZgkSYfBGgU_3mbt7KPmLwU-cHWVmfzIxdhBY8Q3eiqHJK5FELjHkVCnQiiH25FVMknPhOmNjU4b2FjugcbX5yjAGF2jQj9LYtGdT-pBhGqRMxZXpaUpwbEebtwMB_bEBLIrt8sTpRc6zLKXVUoyNyrXwfmnAn7AgbfqZOtxsFjXoUnjCkS5-Icm4xuhJxQmFeGJGHzMp-5RCU789UIH-tIRCmeKjs59K9lU3s_uP7IfSu0Nzt0vVk0njnsoKfO4sin7u0DW92M_QqijSdG8obf14i9YEiy68EVmi8gvbXKeapTXxW4EtHmZamQ-XgVf5uVKzGL4ps0Bmed0LvYOmblHNX4qk1Dg3sdGGz1jcxc0hxWfFpEN4V4mHlMQ4hiG-bhM7qM2LbeIeOqTDSeZkwWVBWt698cApxX7XR5wI8YCE_WkHFW9CKGHVyd6QVV-B1XQLkjtgd1i8QmrgpTpN4sgpU3-GGWslDxaplHsHenfYMjLr8a9eQhSiuuuFRfWSyqHj9HbuiR2BJN1SPjF6nV78EXwcgxqDfQBATvAmJEK-KHZeeJarLcqQ230nUxhtzZTI1YP0_pdprqC2v9bHphiUgMSxA' > /root/.urnetwork/jwt
chmod 600 /root/.urnetwork/jwt

# Start dan enable service
systemctl --user daemon-reexec
systemctl --user daemon-reload
systemctl --user enable urnetwork
systemctl --user start urnetwork
