blank_issues_enabled: true

contact_links:
  - name: Internet Income GitHub FAQ
    url: https://github.com/engageub/InternetIncome/wiki/Frequently-Asked-Questions
    about: Please see the FAQ before raising an issue
  - name: Internet Income GitHub Discussions
    url: https://github.com/engageub/InternetIncome/discussions
    about: Ask questions and get help on GitHub Discussions 
  - name: Formatting proxies for Internet Income
    url: https://github.com/engageub/InternetIncome/wiki/Formatting-proxies-to-user:password@ip:port
    about: Commands to format different types of proxy formats
  - name: Hosts, Proxy and VPN Providers
    url: https://github.com/engageub/InternetIncome/wiki/Proxies-and-Hosting-Providers
    about: List of Providers
